version: '3.7'
services:
  api:
    image: NODE
    build: .
    ports:
      - "8080:8080"
    depends_on:
    - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
